import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {Home,Compass,MessageCircle,Bell,User,LogOut,Search,Send,Check,X,Phone,Video,Mic,MicOff,Camera,CameraOff,PhoneOff} from 'lucide-react';
import './style.css';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=(url&&key)?createClient(url,key):null;

function Auth({onLogin}){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),[msg,setMsg]=useState('');
 async function submit(e){e.preventDefault();if(!supabase)return setMsg('Add Supabase environment variables first.');let r;if(mode==='reset'){r=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin});setMsg(r.error?.message||'Reset email sent.');return}if(mode==='signup')r=await supabase.auth.signUp({email,password,options:{data:{username}}});else r=await supabase.auth.signInWithPassword({email,password});if(r.error)setMsg(r.error.message);else if(mode==='login'&&r.data.session)onLogin(r.data.session.user);else setMsg(mode==='signup'?'Account created. Check your email.':'Done.')} 
 return <main className="auth"><div className="brand">BS<span>.</span>World</div><div className="authcard"><h1>{mode==='reset'?'Reset password':mode==='signup'?'Create account':'Welcome back'}</h1><p>Connect with people around the world.</p><form onSubmit={submit}>{mode==='signup'&&<input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/>{mode!=='reset'&&<input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/>}<button className="primary">{mode==='reset'?'Send reset email':mode==='signup'?'Sign up':'Log in'}</button></form>{msg&&<div className="notice">{msg}</div>}<button className="link" onClick={()=>{setMsg('');setMode(mode==='reset'?'login':'reset')}}>{mode==='reset'?'Back to login':'Forgot password?'}</button>{mode!=='reset'&&<button className="link" onClick={()=>{setMsg('');setMode(mode==='signup'?'login':'signup')}}>{mode==='signup'?'Already have an account? Log in':'Create a new account'}</button>}</div></main>}

function Call({state,onEnd}){const localRef=useRef(null),remoteRef=useRef(null);useEffect(()=>{if(localRef.current&&state.stream)localRef.current.srcObject=state.stream;if(remoteRef.current&&state.remoteStream)remoteRef.current.srcObject=state.remoteStream},[state.stream,state.remoteStream]);return <div className="callOverlay"><div className="callCard"><div className="callTitle"><div><b>{state.other?.name||state.other?.username||'Call'}</b><small>{state.connected?'Connected':'Calling…'} · {state.kind==='video'?'Video':'Voice'}</small></div><button className="icon danger" onClick={onEnd}><PhoneOff/></button></div>{state.kind==='video'?<div className="videos"><video ref={remoteRef} autoPlay playsInline className="remote"/><video ref={localRef} autoPlay playsInline muted className="local"/></div>:<div className="voiceCircle">{(state.other?.name||state.other?.username||'?')[0]?.toUpperCase()}</div>}<div className="callControls"><button className="icon" onClick={state.toggleMute}><state.MutedIcon/></button>{state.kind==='video'&&<button className="icon" onClick={state.toggleCamera}><state.CameraIcon/></button>}<button className="icon danger" onClick={onEnd}><PhoneOff/></button></div></div></div>}

function App({user,onLogout}){const [tab,setTab]=useState('Home'),[profile,setProfile]=useState(null),[users,setUsers]=useState([]),[search,setSearch]=useState(''),[requests,setRequests]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[editing,setEditing]=useState(false),[call,setCall]=useState(null),[incoming,setIncoming]=useState(null);const callRef=useRef(null);
 useEffect(()=>{loadProfile();loadUsers();loadRequests();if(!supabase)return;const events=supabase.channel(`events:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'connection_requests',filter:`receiver_id=eq.${user.id}`},loadRequests).on('broadcast',{event:'call-invite'},({payload})=>{if(payload.to===user.id)setIncoming(payload)}).on('broadcast',{event:'call-accepted'},async({payload})=>{if(callRef.current?.id===payload.callId){const c=callRef.current;if(!c.pc)await setupPeer(c,true)}}).on('broadcast',{event:'call-end'},({payload})=>{if(callRef.current?.id===payload.id)endCall(false)}).subscribe();return()=>supabase.removeChannel(events)},[user.id]);
 async function loadProfile(){let {data}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!data){await supabase.from('profiles').insert({id:user.id,username:user.user_metadata?.username||user.email?.split('@')[0]});data=(await supabase.from('profiles').select('*').eq('id',user.id).single()).data}setProfile(data)}
 async function loadUsers(){const {data}=await supabase.from('profiles').select('*').neq('id',user.id).limit(100);setUsers(data||[])}
 async function loadRequests(){const {data}=await supabase.from('connection_requests').select('*').eq('receiver_id',user.id).eq('status','pending').order('created_at',{ascending:false});setRequests(data||[])}
 async function connect(id){const {data:c}=await supabase.from('connections').select('connected_user_id').eq('user_id',user.id).eq('connected_user_id',id).maybeSingle();if(c)return alert('Already connected.');const {data:p}=await supabase.from('connection_requests').select('id,status').or(`and(sender_id.eq.${user.id},receiver_id.eq.${id}),and(sender_id.eq.${id},receiver_id.eq.${user.id})`).in('status',['pending','accepted']).maybeSingle();if(p)return alert(p.status==='accepted'?'Already connected.':'Request already exists.');const {error}=await supabase.from('connection_requests').insert({sender_id:user.id,receiver_id:id,status:'pending'});if(error)alert(error.message);else setUsers(x=>x.map(u=>u.id===id?{...u,_pending:true}:u))}
 async function respond(r,accept){if(accept){const {error}=await supabase.rpc('accept_connection_request',{request_id:r.id});if(error)return alert(error.message)}else{const {error}=await supabase.from('connection_requests').update({status:'declined'}).eq('id',r.id);if(error)return alert(error.message)}loadRequests()}
 async function getConversation(other){const {data:c,error}=await supabase.rpc('get_or_create_conversation',{other_user_id:other.id});if(error){alert(error.message);return null}return c}
 async function openChat(other){const c=await getConversation(other);if(!c)return;setSelected(other);setTab('Chats');const {data:m}=await supabase.from('messages').select('*').eq('conversation_id',c).order('created_at');setMessages(m||[]);if(window.__chatChannel)supabase.removeChannel(window.__chatChannel);window.__chatChannel=supabase.channel(`chat:${c}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${c}`},p=>setMessages(x=>x.some(m=>m.id===p.new.id)?x:[...x,p.new])).subscribe()}
 async function send(){if(!text.trim()||!selected)return;const c=await getConversation(selected);if(!c)return;const body=text.trim();setText('');const {data,error}=await supabase.from('messages').insert({conversation_id:c,sender_id:user.id,body}).select().single();if(error){setText(body);alert(error.message)}else setMessages(x=>x.some(m=>m.id===data.id)?x:[...x,data])}
 async function saveProfile(e){e.preventDefault();const fd=new FormData(e.currentTarget);const {data,error}=await supabase.from('profiles').update({name:fd.get('name'),username:fd.get('username'),country:fd.get('country'),bio:fd.get('bio'),updated_at:new Date().toISOString()}).eq('id',user.id).select().single();if(error)alert(error.message);else{setProfile(data);setEditing(false);loadUsers()}}
 async function startCall(kind,other=selected){if(!other)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});const id=crypto.randomUUID();const state={id,kind,other,stream,remoteStream:new MediaStream(),connected:false,muted:false,cameraOn:kind==='video'};callRef.current=state;setCall(state);const channel=supabase.channel(`call:${id}`);state.channel=channel;channel.on('broadcast',{event:'signal'},async({payload})=>await handleSignal(payload,state)).on('broadcast',{event:'accepted'},async()=>{if(callRef.current?.id===id&&!state.pc){await setupPeer(state,true)}}).on('broadcast',{event:'end'},()=>endCall(false)).subscribe(async(status)=>{if(status==='SUBSCRIBED'){await supabase.channel(`events:${other.id}`).send({type:'broadcast',event:'call-invite',payload:{to:other.id,from:user.id,fromName:profile?.name||profile?.username,callId:id,kind}})}})}catch(e){alert('Camera/microphone permission is required for calling.')}}
 async function acceptCall(){if(!incoming)return;const {data:other}=await supabase.from('profiles').select('*').eq('id',incoming.from).single();try{const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:incoming.kind==='video'});const state={id:incoming.callId,kind:incoming.kind,other,stream,remoteStream:new MediaStream(),connected:false,muted:false,cameraOn:incoming.kind==='video',callee:true};callRef.current=state;setIncoming(null);setCall(state);const channel=supabase.channel(`call:${state.id}`);state.channel=channel;channel.on('broadcast',{event:'signal'},async({payload})=>await handleSignal(payload,state)).on('broadcast',{event:'end'},()=>endCall(false)).subscribe(async status=>{if(status==='SUBSCRIBED'){const ev=supabase.channel(`events:${other.id}`);await ev.subscribe();await ev.send({type:'broadcast',event:'call-accepted',payload:{to:other.id,callId:state.id}})}})}catch(e){alert('Camera/microphone permission is required for calling.')}}
 async function setupPeer(state,isCaller){const pc=new RTCPeerConnection(iceServers());state.pc=pc;state.stream.getTracks().forEach(t=>pc.addTrack(t,state.stream));pc.ontrack=e=>{e.streams[0]?.getTracks().forEach(t=>state.remoteStream.addTrack(t));setCall({...state,remoteStream:state.remoteStream,connected:true})};pc.onicecandidate=e=>{if(e.candidate)state.channel.send({type:'broadcast',event:'signal',payload:{type:'ice',candidate:e.candidate,from:user.id}})};pc.onconnectionstatechange=()=>{if(['connected','completed'].includes(pc.connectionState))setCall({...state,connected:true});if(['failed','disconnected','closed'].includes(pc.connectionState))setCall({...state,connected:false})};if(isCaller){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await state.channel.send({type:'broadcast',event:'signal',payload:{type:'offer',sdp:offer,from:user.id}})}}
 async function handleSignal(p,state){if(p.from===user.id)return;if(!state.pc&&p.type!=='offer')return;if(p.type==='offer'){if(!state.pc)await setupPeer(state,false);await state.pc.setRemoteDescription(p.sdp);const answer=await state.pc.createAnswer();await state.pc.setLocalDescription(answer);await state.channel.send({type:'broadcast',event:'signal',payload:{type:'answer',sdp:answer,from:user.id}})}else if(p.type==='answer'){await state.pc?.setRemoteDescription(p.sdp)}else if(p.type==='ice'){try{await state.pc?.addIceCandidate(p.candidate)}catch{}}}
 function iceServers(){try{const custom=import.meta.env.VITE_ICE_SERVERS_JSON;if(custom)return JSON.parse(custom)}catch{}return [{urls:'stun:stun.l.google.com:19302'}]}
 async function endCall(notify=true){const c=callRef.current;if(notify&&c?.channel)await c.channel.send({type:'broadcast',event:'end',payload:{id:c.id}});c?.stream?.getTracks().forEach(t=>t.stop());c?.pc?.close();if(c?.channel)supabase.removeChannel(c.channel);callRef.current=null;setCall(null)}
 function updateCall(p){setCall(s=>{const n={...s,...p};callRef.current=n;return n})}
 const filtered=users.filter(x=>(x.username||'').toLowerCase().includes(search.toLowerCase())||(x.name||'').toLowerCase().includes(search.toLowerCase()));
 return <div className="app"><header><b>BS<span>.</span>World</b><div className="topuser">@{profile?.username||'user'}</div></header><section className="content">
 {tab==='Home'&&<><div className="hero"><small>WORLD COMMUNITY</small><h1>Find your people.</h1><p>Discover new perspectives and build meaningful connections worldwide.</p><button className="primary" onClick={()=>setTab('Discover')}>Explore people</button></div></>}
 {tab==='Discover'&&<><h1>Discover</h1><div className="search"><Search size={18}/><input placeholder="Search people..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="grid">{filtered.map(x=><div className="card" key={x.id}><div className="avatar">{(x.name||x.username||'?')[0].toUpperCase()}</div><b>{x.name||x.username}</b><div className="muted">@{x.username}</div><p>{x.country||'World'} · {x.bio||'Hello from BS.World'}</p><button className="secondary" onClick={()=>connect(x.id)}>{x._pending?'Pending':'Connect'}</button></div>)}</div></>}
 {tab==='Chats'&&<><h1>Chats</h1>{selected?<div className="chat"><div className="chathead"><button className="icon" onClick={()=>setSelected(null)}>←</button><div className="avatar sm">{(selected.name||selected.username||'?')[0]}</div><div><b>{selected.name||selected.username}</b><div className="muted">Private conversation</div></div><span/><button className="icon" onClick={()=>startCall('voice')}><Phone/></button><button className="icon" onClick={()=>startCall('video')}><Video/></button></div><div className="messages">{messages.map(m=><div className={m.sender_id===user.id?'bubble mine':'bubble'} key={m.id}>{m.body}</div>)}</div><div className="composer"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Write a message..."/><button className="primary send" onClick={send}><Send/></button></div></div>:<div className="empty">Open a connected person from Discover.</div>}</>}
 {tab==='Alerts'&&<><h1>Alerts</h1>{requests.length?requests.map(r=><div className="alert" key={r.id}><div><b>New connection request</b><p className="muted">Someone wants to connect with you.</p></div><button onClick={()=>respond(r,true)}><Check/></button><button onClick={()=>respond(r,false)}><X/></button></div>):<div className="empty">No new alerts.</div>}</>}
 {tab==='Profile'&&<><h1>Profile</h1><div className="profile"><div className="avatar big">{(profile?.name||profile?.username||'?')[0]?.toUpperCase()}</div>{editing?<form className="editform" onSubmit={saveProfile}><input name="name" defaultValue={profile?.name||''} placeholder="Name"/><input name="username" defaultValue={profile?.username||''} placeholder="Username" required/><input name="country" defaultValue={profile?.country||''} placeholder="Country"/><textarea name="bio" defaultValue={profile?.bio||''} placeholder="Bio"/><button className="primary">Save profile</button></form>:<><h2>{profile?.name||profile?.username}</h2><p className="muted">@{profile?.username}</p><p>{profile?.bio||'Welcome to BS.World'}</p><button className="secondary" onClick={()=>setEditing(true)}>Edit profile</button></>}<button className="secondary" onClick={onLogout}><LogOut size={17}/> Logout</button></div></>}
 </section>{incoming&&<div className="callOverlay"><div className="callCard"><h2>Incoming {incoming.kind==='video'?'video':'voice'} call</h2><p>{incoming.fromName||'Someone'} is calling you.</p><div className="callActions"><button className="primary" onClick={acceptCall}>Accept</button><button className="secondary" onClick={()=>setIncoming(null)}>Decline</button></div></div></div>}{call&&<Call state={{...call,toggleMute:()=>{call.stream.getAudioTracks().forEach(t=>t.enabled=!t.enabled);updateCall({muted:!call.muted})},MutedIcon:call.muted?MicOff:Mic,toggleCamera:()=>{call.stream.getVideoTracks().forEach(t=>t.enabled=!t.enabled);updateCall({cameraOn:!call.cameraOn})},CameraIcon:call.cameraOn?CameraOff:Camera}} onEnd={()=>endCall(true)}/>}<nav>{[['Home',Home],['Discover',Compass],['Chats',MessageCircle],['Alerts',Bell],['Profile',User]].map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I size={20}/><span>{n}</span>{n==='Alerts'&&requests.length>0&&<i>{requests.length}</i>}</button>)}</nav></div>}
function Root(){const [user,setUser]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setUser(data.session?.user||null);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data.subscription.unsubscribe()},[]);if(loading)return <div className="loading">Loading BS.World…</div>;return user?<App user={user} onLogout={()=>supabase.auth.signOut()}/>:<Auth onLogin={u=>setUser(u)}/>};createRoot(document.getElementById('root')).render(<Root/>);
