create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  name text,
  country text,
  bio text,
  avatar_url text,
  online boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create table if not exists public.connection_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  receiver_id uuid references public.profiles(id) on delete cascade not null,
  status text not null default 'pending' check(status in ('pending','accepted','declined')),
  created_at timestamptz default now(),
  unique(sender_id,receiver_id)
);
create table if not exists public.connections (
  user_id uuid references public.profiles(id) on delete cascade not null,
  connected_user_id uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  primary key(user_id,connected_user_id)
);
create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  user_a uuid references public.profiles(id) on delete cascade not null,
  user_b uuid references public.profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(user_a,user_b)
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references public.conversations(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  body text not null,
  created_at timestamptz default now()
);
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  type text not null,
  title text not null,
  body text,
  read boolean default false,
  created_at timestamptz default now()
);
alter table public.profiles enable row level security;
alter table public.connection_requests enable row level security;
alter table public.connections enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
create policy "profiles readable" on public.profiles for select to authenticated using (true);
create policy "own profile insert" on public.profiles for insert to authenticated with check (id=auth.uid());
create policy "own profile update" on public.profiles for update to authenticated using (id=auth.uid());
create policy "requests visible to participants" on public.connection_requests for select to authenticated using (sender_id=auth.uid() or receiver_id=auth.uid());
create policy "send requests" on public.connection_requests for insert to authenticated with check(sender_id=auth.uid());
create policy "receiver updates requests" on public.connection_requests for update to authenticated using(receiver_id=auth.uid());
create policy "connections visible" on public.connections for select to authenticated using(user_id=auth.uid() or connected_user_id=auth.uid());
create policy "connections insert" on public.connections for insert to authenticated with check(user_id=auth.uid());
create policy "conversation access" on public.conversations for select to authenticated using(user_a=auth.uid() or user_b=auth.uid());
create policy "conversation create" on public.conversations for insert to authenticated with check(user_a=auth.uid() or user_b=auth.uid());
create policy "message read" on public.messages for select to authenticated using(exists(select 1 from public.conversations c where c.id=conversation_id and (c.user_a=auth.uid() or c.user_b=auth.uid())));
create policy "message send" on public.messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.conversations c where c.id=conversation_id and (c.user_a=auth.uid() or c.user_b=auth.uid())));
create policy "own notifications" on public.notifications for select to authenticated using(user_id=auth.uid());
create policy "own notification update" on public.notifications for update to authenticated using(user_id=auth.uid());

-- BS.World v3 secure calling/chat helpers
create or replace function public.accept_connection_request(request_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare r public.connection_requests%rowtype; c uuid;
begin
 select * into r from public.connection_requests where id=request_id and receiver_id=auth.uid() and status='pending' for update;
 if not found then raise exception 'Request not found or already handled'; end if;
 insert into public.connections(user_id,connected_user_id) values(auth.uid(),r.sender_id) on conflict do nothing;
 insert into public.connections(user_id,connected_user_id) values(r.sender_id,auth.uid()) on conflict do nothing;
 insert into public.conversations(user_a,user_b) values(least(auth.uid(),r.sender_id),greatest(auth.uid(),r.sender_id)) on conflict do nothing returning id into c;
 if c is null then select id into c from public.conversations where user_a=least(auth.uid(),r.sender_id) and user_b=greatest(auth.uid(),r.sender_id); end if;
 update public.connection_requests set status='accepted' where id=r.id;
 insert into public.notifications(user_id,type,content) values(r.sender_id,'connection_accepted','Your connection request was accepted.');
 return c;
end $$;

create or replace function public.get_or_create_conversation(other_user_id uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare c uuid;
begin
 if other_user_id=auth.uid() then raise exception 'Invalid user'; end if;
 if not exists(select 1 from public.connections where user_id=auth.uid() and connected_user_id=other_user_id) then raise exception 'You must be connected before chatting'; end if;
 insert into public.conversations(user_a,user_b) values(least(auth.uid(),other_user_id),greatest(auth.uid(),other_user_id)) on conflict do nothing returning id into c;
 if c is null then select id into c from public.conversations where user_a=least(auth.uid(),other_user_id) and user_b=greatest(auth.uid(),other_user_id); end if;
 return c;
end $$;

grant execute on function public.accept_connection_request(uuid) to authenticated;
grant execute on function public.get_or_create_conversation(uuid) to authenticated;
